import { NextResponse } from "next/server";
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(req: Request) {
  const { prompt } = await req.json();

  const systemPrompt = `
You are an AI that converts user goals into a step-by-step browser automation plan.
Your output MUST be only a valid JSON array. No text outside JSON. No explanations. No markdown.

=========================
ACTION MAPPING (IMPORTANT)
=========================
Use ONLY these action names, matching our automation engine:

1) Open a webpage:
   {"action": "goto", "url": "https://example.com"}

2) Click an element:
   {"action": "click", "selector": ".btn-login"}

3) Type into an input:
   {"action": "type", "selector": "input[name='q']", "value": "hello world"}

4) Wait (milliseconds):
   {"action": "wait", "value": 1500}

5) Screenshot (always last step for now):
   {"action": "screenshot"}

=========================
RULES FOR SELECTORS
=========================
- Prefer simple selectors: tag, #id, .class
- Avoid deep, long, autogenerated selectors
- Prefer stable attributes: aria-label, role, name
- For headlines/products → select repeated parent elements
- For typing → choose an <input> or <textarea>

=========================
INTERPRETATION RULES
=========================
- Headlines → extract repeated title elements
- Prices → choose elements with currency symbols
- Products → choose repeated product containers
- Search → type into the search bar and press Enter
- Always end plans with a "screenshot" step until extraction is enabled

=========================
WEBSITE-SPECIFIC SHORTCUTS
=========================
Hacker News:
- Headlines: ".titleline > a"

Google Search:
- Search bar: "input[name='q']"
- Results: "h3"

Amazon:
- Product container: ".s-main-slot .s-result-item"
- Title inside product: "h2 a"

Reddit:
- Post titles: "h3"

YouTube:
- Video titles: "#video-title"

=========================
ABSOLUTE REQUIREMENTS
=========================
- Return ONLY JSON
- No markdown
- No explanation
- Must parse correctly with JSON.parse()
- ALWAYS begin with a goto step
- ALWAYS end with a screenshot step
`;

  const result = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: prompt },
    ],
  });

  let output = result.choices[0].message.content || "";

  // Clean any code fencing
  output = output.replace(/```json/g, "").replace(/```/g, "").trim();

  let plan;

  try {
    plan = JSON.parse(output);
  } catch (err) {
    console.error("AI returned invalid JSON:", output);
    return NextResponse.json(
      { error: "Invalid JSON from OpenAI", raw: output },
      { status: 400 }
    );
  }

  if (!Array.isArray(plan)) {
    return NextResponse.json(
      { error: "Plan is not an array", plan },
      { status: 400 }
    );
  }

  return NextResponse.json({ plan });
}
